version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.21  # Choose your Go version
    working_directory: ~/go/src/github.com/yourusername/yourproject

jobs:
  test:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go mod download
      - run:
          name: Run tests
          command: go test -v ./...

  build:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go mod download
      - run:
          name: Build binary
          command: go build -v -o your_binary_name main.go

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
