http:
  routers:
    frontend:
      rule: "PathPrefix(`/`) && !PathPrefix(`/api`)"
      service: frontend
      entryPoints:
        - web
      priority: 100

    backend:
      rule: "PathPrefix(`/api`) || PathPrefix(`/{path:[a-zA-Z0-9]+}`)"
      service: backend
      entryPoints:
        - web

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5173"  # React dev server
          # - url: "http://frontend:80"               # Production React build

    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8081"
